  - name: Add a new node
    bigip_node:
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      host: "{{ add_node_host  }}"
      name: "{{ add_node_name }}"
      validate_certs: "false"
      state: "{{ state }}"
      monitors:
        - "{{ add_node_monitor }}"
    delegate_to: localhost
