---
- name: Manage a pool
  bigip_pool:
    server: "{{ inventory_hostname }}"
    user: "{{ username }}"
    password: "{{ password }}"
    name: "{{ manage_pool[name] }}"
    validate_certs: "false"
    state: "{{ state }}"
    monitors:
      - "{{ manage_pool[monitor] }}"
    monitor_type: "and_list"
  delegate_to: localhost
...
