---
############
#Add objects
############
- include: bigip_irule/manage_irule.yml
  when: state == "present"

###############
#Remove objects
###############
- include: bigip_irule/manage_irule.yml
  when: state == "absent"
...
