---
############
#Add objects
############
- include_tasks: bigip_node/add_node.yml 
  when: state == "present"

- include_tasks: bigip_pool/manage_pool.yml 
  when: state == "present"

- include_tasks: bigip_pool_member/manage_members.yml 
  when: state == "present"

- include_tasks: bigip_monitor_tcp/manage_tcp_monitor.yml
  when: state == "present"

- include_tasks: bigip_monitor_http/manage_http_monitor.yml
  when: state == "present"

- include_tasks: bigip_virtual_server/manage_vip.yml 
  when: state == "present"


###############
#Remove objects
###############
- include_tasks: bigip_virtual_server/manage_vip.yml
  when: state == "absent"

- include_tasks: bigip_monitor_tcp/manage_tcp_monitor.yml
  when: state == "absent"

- include_tasks: bigip_monitor_http/manage_http_monitor.yml
  when: state == "absent"

- include_tasks: bigip_pool/manage_pool.yml 
  when: state == "absent"

- include_tasks: bigip_node/remove_node.yml 
  when: state == "absent"
...
