---
- name: Manage a VIP
  bigip_virtual_server:
    server: "{{ inventory_hostname }}"
    user: "{{ username }}"
    password: "{{ password }}"
    description: "{{ manage_vip[description] }}"
    destination: "{{ manage_vip[destination] }}"
    name: "{{ manage_vip[name] }}"
    pool: "{{ manage_vip[pool] }}"
    port: "{{ manage_vip[port] }}"
    snat: "{{ manage_vip[snat] }}"
    all_profiles:
      - "{{ manage_vip[all_profiles] }}"
    all_rules:
      - "{{ manage_vip[all_rules] }}"
    validate_certs: "false"
    state: "{{ state }}"
  delegate_to: localhost
...
