---
- name: Manage a VIP
  bigip_virtual_server:
    server: "{{ inventory_hostname }}"
    user: "{{ username }}"
    password: "{{ password }}"
    description: "{{ manage_vip_description }}"
    destination: "{{ manage_vip_destination }}"
    name: "{{ manage_vip_name }}"
    pool: "{{ manage_vip_pool }}"
    port: "{{ manage_vip_port }}"
    snat: "{{ manage_vip_snat }}"
    all_profiles:
      - "{{ manage_vip_all_profiles }}"
    validate_certs: "false"
    state: "{{ state }}"
  delegate_to: localhost
...
