---
- hosts: all
  gather_facts: False
  tasks:
  - name: Add virtual server
    bigip_virtual_server:
      server: "{{ inventory_hostname }}" 
      user: admin
      password: admin
      state: present
      partition: Common
      name: my-virtual-server
      destination: 10.10.10.10
      port: 443
      pool: gray_pool1 
      snat: Automap
      description: Test Virtual Server
      profiles:
        - all_profiles
      policies:
        - all_policies
      enabled_vlans:
        - /Common/vlan10
    delegate_to: localhost
...
