---
- name: Manage members in a pool
  bigip_pool_member:
    server: "{{ inventory_hostname }}"
    user: "{{ username }}"
    password: "{{ password }}"
    host: "{{ manage_members_host }}"
    pool: "{{ manage_members_pool }}"
    port: "{{ manage_members_port }}"
    state: "{{ state }}"
    validate_certs: "false"
  delegate_to: localhost
...
